repositories:
  - prefix: bitnami
    urls:
      - https://charts.bitnami.com/bitnami
  - prefix: jetstack
    urls:
      - https://charts.jetstack.io
  - prefix: jenkins-x
    urls:
      - https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
      - http://chartmuseum.jenkins-x.io
  - prefix: stable
    urls:
      - https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
  - prefix: flagger
    urls:
      - https://flagger.app
